name: Build

on:
  push:
    branches: [main]

permissions:
  contents: read

env:
  IMAGE: ghcr.io/carloslewis-03/secure-pipeline-lab

jobs:
  build:
    runs-on: ubuntu-latest

    # For THIS job only, grant one extra power: upload a package to the registry.
    permissions:
      contents: read
      

    steps:
      - name: Check out my code
        uses: actions/checkout@v4

      - name: Log in to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ env.IMAGE }}:latest .

      - name: Push the image to the registry
        run: docker push ${{ env.IMAGE }}:latest
